// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaLCOke13S5UiUmppUQWfPKXPB0KDW1nU',
    appId: '1:533045523876:web:ad9be55ddc3097dfc5fd31',
    messagingSenderId: '533045523876',
    projectId: 'talktask',
    authDomain: 'talktask.firebaseapp.com',
    storageBucket: 'talktask.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALqEWlPkjC1AsW6Y1ld71bofJa_8EYWjQ',
    appId: '1:533045523876:android:512716a237391894c5fd31',
    messagingSenderId: '533045523876',
    projectId: 'talktask',
    storageBucket: 'talktask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDigo_NNMBk_xpqryVqge20muH5RpL8Rts',
    appId: '1:533045523876:ios:f3b9f027a48d42b5c5fd31',
    messagingSenderId: '533045523876',
    projectId: 'talktask',
    storageBucket: 'talktask.firebasestorage.app',
    iosBundleId: 'com.example.talktask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDigo_NNMBk_xpqryVqge20muH5RpL8Rts',
    appId: '1:533045523876:ios:f3b9f027a48d42b5c5fd31',
    messagingSenderId: '533045523876',
    projectId: 'talktask',
    storageBucket: 'talktask.firebasestorage.app',
    iosBundleId: 'com.example.talktask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaLCOke13S5UiUmppUQWfPKXPB0KDW1nU',
    appId: '1:533045523876:web:a90031e839a883d3c5fd31',
    messagingSenderId: '533045523876',
    projectId: 'talktask',
    authDomain: 'talktask.firebaseapp.com',
    storageBucket: 'talktask.firebasestorage.app',
  );
}
